name: crankin
markdown: redcarpet
pygments: true
permalink: /:year/:month/:day/:title
collections:
  projects:
    output: true
    permalink: /projects/:path/
prose:
  rooturl: '_posts'
  siteurl: 'http://crankin.github.io/blog/'
